# polyglot server
polyglot:
  image: ncsa/polyglot-server
  environment:
    DOWNLOAD_SS_FILE: 'true'
  ports:
    - "8184:8184"
  links:
    - mongo
    - rabbitmq

# example extractor
im:
  image: ncsa/ss-imagemagick
  links:
    - rabbitmq

htmldoc:
  image: ncsa/ss-htmldoc
  links:
    - rabbitmq

# mongo database used to store data
mongo:
  image: mongo:latest

# rabbitmq to connect to extractors
rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672"
    - "15672"
